### ISSUE TITLE
Add a way to serialize documents

### ISSUE THREAD

**Issue by pixelspark** [jeffa5/automerge-persistent#10]
I am testing a scenario in which a server synchronizes documents with clients, with automerge-persistent on the server for persistence. If I understand correctly, newly connected clients would have to be seeded with the binary document as serialized by `Backend::save`. This method however is not available on `PersistentBackend` which wraps the `Backend`.

The referenced pull request adds a `save` method to `PersistentBackend`, making it easy to obtain the binary serialized document.

https://github.com/jeffa5/automerge-persistent/pull/9

**Comment by pixelspark** [comment]
> For syncing you might want to look into the sync protocol,
> 
> https://github.com/jeffa5/automerge-persistent/blob/2ea5324fa5d0d9a845fa5d79c672fa0ad499066d/automerge-persistent/src/lib.rs#L271
> 
> and
> https://github.com/jeffa5/automerge-persistent/blob/2ea5324fa5d0d9a845fa5d79c672fa0ad499066d/automerge-persistent/src/lib.rs#L309
> 
> This handles lots of things like clients already having some changes etc rather than having to manually filter what to send. Would this be more appropriate for your use?

Yes, this is probably what I should use. Am I correct in assuming that `generate_sync_message` will generate a message containing all changes for peer IDs that haven't been seen before (or for any peer whose sync status is unknown)?

Regardless it might still be useful to have a way to serialize the full document to a `Vec<u8>`, e.g. for allowing a download or back-up of a document.

**Comment by jeffa5** [comment]
The `generate_sync_message` function takes a `peer_id` that will identify that peer. I don't think it sends everything straight away, the first message for an unseen peer may just be information about what is in the local document so that later rounds can send only the necessary changes.

> Regardless it might still be useful to have a way to serialize the full document to a Vec<u8>, e.g. for allowing a download or back-up of a document.

Yes, that sounds like a nice use-case. I'll take a look at the PR.

**Comment by jeffa5** [comment]
Merged https://github.com/jeffa5/automerge-persistent/pull/9
